### ISSUE TITLE
加载huggingface上的checkpoint时提示KeyError: 'open-llama'

### ISSUE THREAD

**Issue by xikaluo** [s-JoL/Open-Llama#17]
**运行代码：**
from transformers import AutoModelForCausalLM, AutoTokenizer

tokenizer = AutoTokenizer.from_pretrained("s-JoL/Open-Llama-V1", use_fast=False)
model = AutoModelForCausalLM.from_pretrained("s-JoL/Open-Llama-V1").cuda()

inputs = tokenizer('user:implement quick sort in python\nsystem:', return_tensors='pt', return_attention_mask=False)
for k, v in inputs.items():
   inputs[k] = v.cuda()
pred = model.generate(**inputs, max_new_tokens=512, do_sample=True)
print(tokenizer.decode(pred.cpu()[0]).strip())

**报错：**
Traceback (most recent call last):
  File "/data/rooter_use/Open-Llama/test.py", line 4, in <module>
    model = AutoModelForCausalLM.from_pretrained("s-JoL/Open-Llama-V1").cuda()
  File "/data/wangyanbing/.conda/envs/cyz_py39/lib/python3.9/site-packages/transformers/models/auto/auto_factory.py", line 441, in from_pretrained
    config, kwargs = AutoConfig.from_pretrained(
  File "/data/wangyanbing/.conda/envs/cyz_py39/lib/python3.9/site-packages/transformers/models/auto/configuration_auto.py", line 937, in from_pretrained
    config_class = CONFIG_MAPPING[config_dict["model_type"]]
  File "/data/wangyanbing/.conda/envs/cyz_py39/lib/python3.9/site-packages/transformers/models/auto/configuration_auto.py", line 643, in __getitem__
    raise KeyError(key)
KeyError: 'open-llama'

transformers是通过您在README里的pip install git+https://github.com/s-JoL/transformers.git@dev来进行的安装
猜测是因为config.json里的architectures和model_type与transformers里的字典不匹配？

**Comment by s-JoL** [comment]
我本地测试是没问题的，你是否成功安装了这个版本的transformers？通过pip list | grep transformers查看应该是4.29.0.dev0
