### ISSUE TITLE
v2版训练代码在forward阶段报错

### ISSUE THREAD

**Issue by xikaluo** [s-JoL/Open-Llama#36]
您好，我今天在尝试您的v2版训练代码时，遇到了如下的错误：

> Traceback (most recent call last):
  File "/data/rooter_use/cyz_open_llama/Open-Llama/train_lm.py", line 94, in <module>
    app.run(main)
  File "/data/rooter_use/conda/envs/llama-env39/lib/python3.9/site-packages/absl/app.py", line 308, in run
    _run_main(main, args)
  File "/data/rooter_use/conda/envs/llama-env39/lib/python3.9/site-packages/absl/app.py", line 254, in _run_main
    sys.exit(main(argv))
  File "/data/rooter_use/cyz_open_llama/Open-Llama/train_lm.py", line 90, in main
    trainer.train()
  File "/data/rooter_use/cyz_open_llama/Open-Llama/solver/trainer.py", line 153, in train
    losses = self.train_step(batch)
  File "/data/rooter_use/cyz_open_llama/Open-Llama/solver/trainer.py", line 120, in train_step
    out = self.model(**batch)
  File "/data/rooter_use/conda/envs/llama-env39/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/data/rooter_use/conda/envs/llama-env39/lib/python3.9/site-packages/deepspeed/utils/nvtx.py", line 15, in wrapped_fn
    ret_val = func(*args, **kwargs)
  File "/data/rooter_use/conda/envs/llama-env39/lib/python3.9/site-packages/deepspeed/runtime/engine.py", line 1675, in forward
    loss = self.module(*inputs, **kwargs)
  File "/data/rooter_use/conda/envs/llama-env39/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/data/rooter_use/conda/envs/llama-env39/lib/python3.9/site-packages/transformers/models/open_llama/modeling_open_llama.py", line 725, in forward
    outputs = self.model(
  File "/data/rooter_use/conda/envs/llama-env39/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/data/rooter_use/conda/envs/llama-env39/lib/python3.9/site-packages/transformers/models/open_llama/modeling_open_llama.py", line 612, in forward
    layer_outputs = decoder_layer(
  File "/data/rooter_use/conda/envs/llama-env39/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/data/rooter_use/conda/envs/llama-env39/lib/python3.9/site-packages/transformers/models/open_llama/modeling_open_llama.py", line 315, in forward
    hidden_states, self_attn_weights, present_key_value = self.self_attn(
  File "/data/rooter_use/conda/envs/llama-env39/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/data/rooter_use/conda/envs/llama-env39/lib/python3.9/site-packages/transformers/models/open_llama/modeling_open_llama.py", line 232, in forward
    attn_output = xops.memory_efficient_attention(query_states, key_states, value_states,
  File "/data/rooter_use/conda/envs/llama-env39/lib/python3.9/site-packages/xformers/ops/fmha/__init__.py", line 197, in memory_efficient_attention
    return _memory_efficient_attention(
  File "/data/rooter_use/conda/envs/llama-env39/lib/python3.9/site-packages/xformers/ops/fmha/__init__.py", line 298, in _memory_efficient_attention
    return _fMHA.apply(
  File "/data/rooter_use/conda/envs/llama-env39/lib/python3.9/site-packages/xformers/ops/fmha/__init__.py", line 43, in forward
    out, op_ctx = _memory_efficient_attention_forward_requires_grad(
  File "/data/rooter_use/conda/envs/llama-env39/lib/python3.9/site-packages/xformers/ops/fmha/__init__.py", line 323, in _memory_efficient_attention_forward_requires_grad
    op = _dispatch_fw(inp)
  File "/data/rooter_use/conda/envs/llama-env39/lib/python3.9/site-packages/xformers/ops/fmha/dispatch.py", line 95, in _dispatch_fw
    return _run_priority_list(
  File "/data/rooter_use/conda/envs/llama-env39/lib/python3.9/site-packages/xformers/ops/fmha/dispatch.py", line 70, in _run_priority_list
    raise NotImplementedError(msg)
NotImplementedError: No operator found for `memory_efficient_attention_forward` with inputs:
     query       : shape=(2, 2048, 4, 192) (torch.bfloat16)
     key         : shape=(2, 2048, 4, 192) (torch.bfloat16)
     value       : shape=(2, 2048, 4, 192) (torch.bfloat16)
     attn_bias   : <class 'xformers.ops.fmha.common.LowerTriangularMask'>
     p           : 0.1
`cutlassF` is not supported because:
    dropout > 0.0
`flshattF` is not supported because:
    max(query.shape[-1] != value.shape[-1]) > 128
`tritonflashattF` is not supported because:
    max(query.shape[-1] != value.shape[-1]) > 128
    dropout > 0.0
    requires A100 GPU
`smallkF` is not supported because:
    dtype=torch.bfloat16 (supported: {torch.float32})
    max(query.shape[-1] != value.shape[-1]) > 32
    attn_bias type is <class 'xformers.ops.fmha.common.LowerTriangularMask'>
    unsupported embed per head: 192

想请教一下，这个错误日志里除了requires A100以外，其它的问题是由什么导致的？我使用的accelerate config和您提供的一样，模型config为：

> data:
  mode: "pretrain"
  data: 
    wudao: "/data/rooter_use/Open-Llama/data/pretrain_data/part-wudao*.jsonl.zst"
    # 由于加载了Llama模型的ckpt所以只使用少量英文数据
    # the_pile: "data/pretrain_data/part-pile-1*.jsonl.zst"
  pad_to_max: False
  sequence_sample_mode: "none"
  concat_multiple_sequence: True
  num_sequences: 10
  seq_length: 2048
  tokenizer_model_path: "configs/llama_tokenizer_extended.model"
model:
  initializer_range: 1.0e-2
  hidden_dropout_prob: 0.1
  attention_dropout_prob: 0.1
  use_stable_embedding: False
  shared_input_output_embedding: False
  hidden_size: 768
  num_hidden_layers: 6
  num_attention_heads: 4
  intermediate_size: 2048
train:
  train_batch_size: 2
  num_training_steps: 500000
  num_warmup_steps: 2000
  initializer_range: 1.0e-2
  lr: 2.0e-4
  weight_decay: 1.0e-1
    # 加载预训练权重，从头训练设为null
    # ckpt: "data/llama_raw_ckpt/7B/extended.pth"
  ckpt: null
  train_num_workers: 16
  gradient_accumulation_steps: 12
  prefetch_factor: 100
  log_interval: 5
  eval_interval: 500
  save_interval: 1000
  work_dir: "data/saved_ckpt/small"
  project_name: "Llama Pretrain"

按照报错日志来看，似乎有一些问题是由于模型config的配置不符合xformers要求导致的？

**Comment by s-JoL** [comment]
看报错是每个head分到的hidden size太大了，你要不试试把num_attention_heads增大到8，或者把attention_dropout_prob设为0

**Comment by xikaluo** [comment]
> 看报错是每个head分到的hidden size太大了，你要不试试把num_attention_heads增大到8，或者把attention_dropout_prob设为0

num_attention_heads增大到16就可以了，十分感谢
